package config

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"gopkg.in/yaml.v3"
)

// Config holds all configuration for the dbx CLI.
type Config struct {
	Host           string        `yaml:"host"`
	Token          string        `yaml:"token"`
	WarehouseID    string        `yaml:"warehouse_id"`
	DefaultCatalog string        `yaml:"default_catalog"`
	AllowedSchemas []string      `yaml:"allowed_schemas"`
	DefaultFormat  string        `yaml:"default_format"`
	QueryTimeout   time.Duration `yaml:"query_timeout"`
	MaxRows        int64         `yaml:"max_rows"`
}

// Load reads configuration from defaults, an optional YAML file, and
// environment variable overrides, in that order. Later sources win.
func Load() (*Config, error) {
	// 1. Start with defaults.
	cfg := &Config{
		DefaultFormat: "table",
		QueryTimeout:  30 * time.Second,
		MaxRows:       10000,
	}

	// 2. Try loading YAML config file.
	configPath := os.Getenv("DBX_CONFIG_PATH")
	if configPath == "" {
		home, err := os.UserHomeDir()
		if err != nil {
			return nil, fmt.Errorf("determining home directory: %w", err)
		}
		configPath = filepath.Join(home, ".dbx", "config.yaml")
	}

	data, err := os.ReadFile(configPath)
	if err == nil {
		if err := yaml.Unmarshal(data, cfg); err != nil {
			return nil, fmt.Errorf("parsing config file %s: %w", configPath, err)
		}
	} else if !os.IsNotExist(err) {
		return nil, fmt.Errorf("reading config file %s: %w", configPath, err)
	}
	// If the file doesn't exist, we silently continue with defaults.

	// 3. Override with environment variables.
	if v := os.Getenv("DATABRICKS_HOST"); v != "" {
		cfg.Host = v
	}
	if v := os.Getenv("DATABRICKS_TOKEN"); v != "" {
		cfg.Token = v
	}
	if v := os.Getenv("DATABRICKS_WAREHOUSE_ID"); v != "" {
		cfg.WarehouseID = v
	}
	if v := os.Getenv("DBX_ALLOWED_SCHEMAS"); v != "" {
		cfg.AllowedSchemas = strings.Split(v, ",")
	}
	if v := os.Getenv("DBX_DEFAULT_CATALOG"); v != "" {
		cfg.DefaultCatalog = v
	}

	return cfg, nil
}

// Save writes the configuration to ~/.dbx/config.yaml.
func (c *Config) Save() error {
	home, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("finding home directory: %w", err)
	}
	configDir := filepath.Join(home, ".dbx")
	if err := os.MkdirAll(configDir, 0o700); err != nil {
		return fmt.Errorf("creating config directory: %w", err)
	}

	yamlCfg := struct {
		Host           string   `yaml:"host"`
		Token          string   `yaml:"token"`
		WarehouseID    string   `yaml:"warehouse_id"`
		DefaultCatalog string   `yaml:"default_catalog,omitempty"`
		AllowedSchemas []string `yaml:"allowed_schemas,omitempty"`
		DefaultFormat  string   `yaml:"default_format"`
		QueryTimeout   string   `yaml:"query_timeout"`
		MaxRows        int64    `yaml:"max_rows"`
	}{
		Host:           c.Host,
		Token:          c.Token,
		WarehouseID:    c.WarehouseID,
		DefaultCatalog: c.DefaultCatalog,
		AllowedSchemas: c.AllowedSchemas,
		DefaultFormat:  c.DefaultFormat,
		QueryTimeout:   c.QueryTimeout.String(),
		MaxRows:        c.MaxRows,
	}

	data, err := yaml.Marshal(yamlCfg)
	if err != nil {
		return fmt.Errorf("marshaling config: %w", err)
	}

	configPath := filepath.Join(configDir, "config.yaml")
	header := "# dbx configuration\n# Generated by: dbx-cli\n# You can also override values with environment variables:\n#   DATABRICKS_HOST, DATABRICKS_TOKEN, DATABRICKS_WAREHOUSE_ID\n\n"

	if err := os.WriteFile(configPath, []byte(header+string(data)), 0o600); err != nil {
		return fmt.Errorf("writing config: %w", err)
	}
	return nil
}

// Validate checks that required configuration fields are set.
func (c *Config) Validate() error {
	var missing []string
	if c.Host == "" {
		missing = append(missing, "host (set DATABRICKS_HOST or host in config.yaml)")
	}
	if c.Token == "" {
		missing = append(missing, "token (set DATABRICKS_TOKEN or token in config.yaml)")
	}
	if c.WarehouseID == "" {
		missing = append(missing, "warehouse_id (set DATABRICKS_WAREHOUSE_ID or warehouse_id in config.yaml)")
	}
	if len(missing) > 0 {
		return fmt.Errorf("missing required config: %s", strings.Join(missing, "; "))
	}
	return nil
}
